name = "GraphNetSim"
uuid = "5ff66f56-808c-48e7-ac84-dd29877231f8"
version = "0.1.0"
authors = ["JK <Josef.Kircher@uni-a.de", "JT <julian.trommer@informatik.uni-augsburg.de>"]

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GraphNetCore = "7809f980-de1b-4f9a-8451-85f041491431"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PointNeighbors = "1c4d5385-0a27-49de-8e2c-43b175c8985c"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
cuDNN = "02a925ec-e4fe-4b08-9a7e-0d78e3d38ccd"

[compat]
Adapt = "4.3.0"
Aqua = "0.8"
CSV = "0.10.15"
CUDA = "5.5.2"
ChainRulesCore = "1.16.0 - 1"
ComponentArrays = "0.15.31"
DataFrames = "1.6"
DataInterpolations = "8.6.0"
Distributions = "0.25"
HDF5 = "0.17"
JLD2 = "0.5"
JSON = "0.21"
JuliaFormatter = "2.2.1"
KernelAbstractions = "0.9.39"
LinearAlgebra = "<1.12.0"
Lux = "1.4 - 1"
LuxCUDA = "0.3"
MLUtils = "0.4.4 - 0.4"
NearestNeighbors = "0.4.27"
Optimisers = "0.4"
OrdinaryDiffEq = "6.85 - 6"
Plots = "1.40.18"
PointNeighbors = "0.6.3"
PreallocationTools = "0.4.34"
Printf = "1"
ProgressMeter = "1.7.0 - 1"
Random = "1"
RecursiveArrayTools = "3.36.0"
SciMLBase = "2.7.0 - 2"
SciMLSensitivity = "7.76 - 7"
Statistics = "1"
Test = "1"
Zygote = "0.6"
cuDNN = "1.4"
julia = "1.12"

[sources]
GraphNetCore = {url = "https://github.com/una-auxme/GraphNetCore.jl", rev = "GNS-small-graph"}

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
